import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import '@/styles/globals.css'
import { Contact, Footer, Navigation } from '@/components'
import Providers from '@/app/providers'

const poppins = Roboto({
  // weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const showTopButton = true
  return (
    <html lang='en' dir='ltr' suppressHydrationWarning={true}>
      <body className={poppins.className}>
        <Providers>
          <Navigation />
          {children}
          <Contact />
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
