export { default as Navigation } from './navigation'
export { default as HeroSection } from './hero-section'
export { default as Contact } from './contact'
export { default as Footer } from './footer'
export { default as SocialMedia } from './ui/social-media'
export { default as Icon } from './ui/icon'
export { default as Star } from './icons/star'
