export { default as Github } from './github'
export { default as Linkedin } from './linkedin'
export { default as Mail } from './mail'
export { default as Menu } from './menu'
export { default as Moon } from './moon'
export { default as Sun } from './sun'
export { default as Whatsapp } from './whatsapp'
export * from './style'
